module.exports = {
    INVALID_URL: "INVALID REQUEST",
    CONNETION_ERROR : "CONNETION_ERROR",
    CONNETION_SUCCESS : "CONNETION_SUCCESS",

    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    INVALID_TOKEN: "INVALID_TOKEN",
    INVALID_USER_ACCESS: "INVALID_USER_ACCESS",
    
    INVALID_PAYLOAD_PROVIDED: {
        code: 406,
        message: "INVALID PAYLOAD PROVIDED"
    },

    INVALID_USER_REQUEST_ACCESS: {
        code: 404,
        message: "INVALID_USER_ACCESS"
    }
}